import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Buttons from "./buttons";
import Grid from "@mui/material/Grid";

export default function Home() {
  return (
    <>
      <Head>
        <title>Calc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        direction="column"
        justifyContent="center"
        alignItems="center"
        className={styles.container}
      >
        <Buttons />
      </Grid>
    </>
  );
}
